// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Model.AppealsModel.Appeal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("fio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<string>("telephone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("status_id");

                    b.ToTable("appeals_20ai24ppy");
                });

            modelBuilder.Entity("Entities.Model.StatusesModel.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("statuses_20ai24ppy");

                    b.HasData(
                        new
                        {
                            id = 1,
                            status = "active"
                        },
                        new
                        {
                            id = 2,
                            status = "readed"
                        },
                        new
                        {
                            id = 3,
                            status = "talked"
                        },
                        new
                        {
                            id = 4,
                            status = "rejected"
                        },
                        new
                        {
                            id = 5,
                            status = "consent"
                        });
                });

            modelBuilder.Entity("Entities.Model.UserTypesModel.UserType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users_types_20ai24ppy");

                    b.HasData(
                        new
                        {
                            id = 1,
                            type = "admin"
                        });
                });

            modelBuilder.Entity("Entities.Model.UsersModel.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("token")
                        .HasColumnType("text");

                    b.Property<int?>("user_type_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("login")
                        .IsUnique();

                    b.HasIndex("user_type_id");

                    b.ToTable("user_20ai24ppy");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "aippy@gmail.com",
                            login = "admin",
                            password = "PJwNvVwgDOlqB++936LTEcR5HX22nFeLDlnopfT4Syg=",
                            user_type_id = 1
                        });
                });

            modelBuilder.Entity("Entities.Model.AppealsModel.Appeal", b =>
                {
                    b.HasOne("Entities.Model.StatusesModel.Status", "status_")
                        .WithMany()
                        .HasForeignKey("status_id");

                    b.Navigation("status_");
                });

            modelBuilder.Entity("Entities.Model.UsersModel.User", b =>
                {
                    b.HasOne("Entities.Model.UserTypesModel.UserType", "user_type_")
                        .WithMany()
                        .HasForeignKey("user_type_id");

                    b.Navigation("user_type_");
                });
#pragma warning restore 612, 618
        }
    }
}
